services:
  - type: web
    name: courierops-backend
    env: node
    region: singapore   # closest to India
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false        # set manually in Render dashboard
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 7d
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE
        sync: false
      - key: FRONTEND_URL
        sync: false        # your Vercel frontend URL
